AspNetIdentityUsers/AspNetIdentityUsers/Controllers/RoleAdminController.cs
using AspNetIdentityUsers.Infrastructure;
using AspNetIdentityUsers.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AspNetIdentityUsers.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class RoleAdminController : Controller
    {
        private AppUserManager UserManager => HttpContext.GetOwinContext().GetUserManager<AppUserManager>();

        private AppRoleManager RoleManager => HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        public ActionResult Index() => View(RoleManager.Roles);

        public ActionResult Create() => View();

        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result =
                    await RoleManager.CreateAsync(new AppRole(name));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }

            return View(name);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            AppRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new[] { "Role not found" });
            }
        }

        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            var memberIds = role.Users
                .Select(x => x.UserId)
                .ToArray();

            var members = UserManager.Users
                .Where(x => memberIds.Any(y => y == x.Id));

            var nonMembers = UserManager.Users.Except(members);

            return View(new RoleEditViewModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationViewModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (var userId in model.IdsToAdd ?? new string[] { })
                {
                    result = await UserManager.AddToRoleAsync(userId, model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }

                foreach (var userId in model.IdsToDelete ?? new string[] { })
                {
                    result = await UserManager.RemoveFromRoleAsync(userId, model.RoleName);

                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }

                return RedirectToAction("Index");
            }

            return View("Error", new[] { "Role not found" });
        }
    }
}

AspNetIdentityUsers/AspNetIdentityUsers/Views/RoleAdmin/Create.cshtml
@model string

@{
    ViewBag.Title = "Create Role";
}

<h2>Create Role</h2>

@Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control"/>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

AspNetIdentityUsers/AspNetIdentityUsers/Views/RoleAdmin/Edit.cshtml
@model AspNetIdentityUsers.Models.RoleEditViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h2>Edit Role</h2>
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name"/>
    <div class="panel panel-primary">
        <div class="panel-heading">Add to Role <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr>
                    <td colspan="2">All users in Role</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User Id</td>
                    <td>Add to Role</td>
                </tr>
                foreach (var user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id" />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">Remove from Role <b>@Model.Role.Name</b></div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr>
                    <td colspan="2">No Users in Role</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User Id</td>
                    <td>Remove from Role</td>
                </tr>
                foreach (var user in Model.Members)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToDelete" value="@user.Id" />
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

AspNetIdentityUsers/AspNetIdentityUsers/Views/RoleAdmin/Index.cshtml
@using AspNetIdentityUsers.Models
@using AspNetIdentityUsers.Infrastructure
@model IEnumerable<AppRole>

@{
    ViewBag.Title = "Roles";
}

<div class="panel panel-primary">
    <div class="panel-heading">Roles</div>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Users</th>
            <th style="min-width: 150px"></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center">No Roles</td>
            </tr>
        }
        else
        {
            foreach (var role in Model)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td>
                        @if (role.Users == null || role.Users.Count == 0)
                        {
                            @: No Users in Role
                        }
                        else
                        {
                            <p>
                                @string.Join(", ", role.Users.Select(x => Html.GetUserName(x.UserId)))
                            </p>
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id }))
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = role.Id }, new { @class = "btn btn-primary btn-xs", style="float:left; margin-right:5px"})
                            <button class="btn btn-danger btn-xs" type="submit">Delete</button>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>
@Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })